# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dual/cs5170403/COL216/COL216_Assn_9/COL216_Assn_9.srcs/sources_1/ip/unified_memory/unified_memory.xci
# IP: The module: 'unified_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dual/cs5170403/COL216/COL216_Assn_9/COL216_Assn_9.srcs/sources_1/ip/unified_memory/unified_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unified_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dual/cs5170403/COL216/COL216_Assn_9/COL216_Assn_9.srcs/sources_1/ip/unified_memory/unified_memory.xci
# IP: The module: 'unified_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dual/cs5170403/COL216/COL216_Assn_9/COL216_Assn_9.srcs/sources_1/ip/unified_memory/unified_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unified_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
