# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/COL216_Assn_7/assn_7.xdc

# IP: ip/unified_memory/unified_memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unified_memory || ORIG_REF_NAME==unified_memory}]
