# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.cache/wt [current_project]
set_property parent.project_path /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/dual/cs5170403/COL216/COL216_assn_5/array_sum_bin.coe
read_vhdl -library xil_defaultlib {
  /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/imports/COL216_Assn_7/clock_divider.vhf
  /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/imports/COL216_Assn_7/register_file.vhd
  /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/imports/COL216_Assn_7/instr_decoder.vhf
  /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/imports/COL216_Assn_7/exec_state_fsm.vhd
  /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/imports/COL216_Assn_7/control_state_fsm.vhd
  /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/imports/COL216_Assn_7/ALU.vhd
  /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/imports/COL216_Assn_7/debouncer.vhf
  /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/imports/COL216_Assn_7/Data_path.vhd
}
read_ip -quiet /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/ip/unified_memory/unified_memory.xci
set_property used_in_implementation false [get_files -all /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/ip/unified_memory/unified_memory_ooc.xdc]
set_property is_locked true [get_files /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/sources_1/ip/unified_memory/unified_memory.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/constrs_1/imports/COL216_Assn_7/assn_7.xdc
set_property used_in_implementation false [get_files /home/dual/cs5170403/COL216/COL216_Assn_7/COL216_Assn_7.srcs/constrs_1/imports/COL216_Assn_7/assn_7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
